### ISSUE TITLE
Checkout - Mobile app credit card form unstable

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#100] opened 2019-04-10 22:36 UTC
Tested on Live iOS app on iPhone 7

Trying to enter the payment in the CC field is having issues:
- Tapping into the field works some of the time, often requires multiple attempts to get to focus on the field, sometimes gets focus openning the keyboard and then immediately closing the keyboard and losing focus
- Instead of automatically moving to the next input field after typing information in, it closes the keyboard requiring clicking into the next input field
- The payment method icon always shows the Visa icon even when the payment method is amex or mastercard

created revelrylabs/bn-mobile-react#712

**Comment by Tas4tari** [comment] 2019-07-26 07:42
Duplicate off issue 91, this has been closed

**Closed by Tas4tari** 2019-07-26 07:42 UTC
Labels: bug, ios
