### ISSUE TITLE
Ticket Transfer - On devices with zoomed text/accessibility mode transfer button is off screen and can't get through transfer process

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#109] opened 2019-04-11 21:46 UTC
a customer noted that since they have their phone font size set to large, the transfer button on the transfer page clips off the screen and cannot be clicked. The customer said they have bad eyesight, so they usually need the large font, but once they decreased the font size for their phone UI, the transfer button appeared fine.

**Comment by zmelamed** [comment] 2019-04-11 21:50
created revelrylabs/bn-mobile-react#717

**Comment by Tas4tari** [comment] 2019-07-26 07:44
Duplicate of issue 90, closing this

**Closed by Tas4tari** 2019-07-26 07:44 UTC
Labels: android, bug, ios
