### ISSUE TITLE
Mobile Guest List - A door person should be able to search by First Name, Last Name, or Full name

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#165] opened 2019-05-16 18:40 UTC
**Context:** Currently you can only search by first name, as soon as you enter a space to begin typing the last name the results disappear. Typing just the last name returns no results.

**Acceptance Criteria:**
A door person should be able to find tickets belonging to John Smith by typing "John", "john s", "john smith", or "Smith"

related to ticket revelrylabs/bn-mobile-react#786

**Comment by Anziskavds** [comment] 2019-05-23 08:53
Also happening on Box Office guest list on web

**Comment by harrisonlemon** [comment] 2019-05-23 17:14
Screengrab of Studio Box office behavior: https://cl.ly/b0a34e8520cc

App check-in tbd - test app access pending

**Comment by Timo614** [comment] 2019-05-23 18:28
It looks like the web for some reason doesn't use the query parameter of the API and instead does its own search locally (I guess for speed purposes?). I'll file a quick issue and push up a fix for that as well. The mobile one mentioned here should be set though as it hits the API directly.

**Comment by Anziskavds** [comment] 2019-06-03 10:52
Steps to reproduce:

-Issue still occur.
-The door person can only search by first name or last name at a time. 
-The door person can't search by both first or last name.
-This is on web and mobile web.

https://cl.ly/4c79411d7985

https://cl.ly/1636ebe198bf

**Comment by Timo614** [comment] 2019-06-03 11:11
@Anziskavds you're searching by "LastName FirstName" there. 

> A door person should be able to find tickets belonging to John Smith by typing "John", "john s", "john smith", or "Smith"

![Screen Shot 2019-06-03 at 7 07 08 AM](https://user-images.githubusercontent.com/1319304/58797530-39251700-85ce-11e9-8dcd-99acc70bd428.png)

We can add it just wasn't mentioned originally as case to handle here. Normally people search using the first name prior. I guess from an international point of view some countries like Japan use last name prior so it may be more natural to lookup that way.

**Comment by nine-tari** [comment] 2019-06-03 12:12
Pushed up new PRs to address this new scenario we added here to do last name first searches. Removed the failed QA and will push it into that pile again pending their merging.

**Comment by nine-tari** [comment] 2019-06-04 13:07
Both the api and web branches to add support for last name prior to first name have been merged.

**Comment by Anziskavds** [comment] 2019-06-05 06:31
Steps to reproduce:

- Door person can search for a guest in the guest list by first name and last name, last name and first name, last name and initials, initial and surname or by just the first name or last name on Develop environment.
-Door person can search for a guest in the guest list by only first name and last name, initial and last name, last name and initial or by just the first name or last name, it doesn't give any results if you search by the last name and then first name. This is both on Prod and Beta.

**Comment by Anziskavds** [comment] 2019-06-05 10:33
Reviewed and found that is working on the latest API 1.0.134

**Comment by Tas4tari** [comment] 2019-06-13 07:26
This has been released

**Closed by Tas4tari** 2019-06-13 07:26 UTC
Labels: Client Reported, bug, epic, in progress, web
