### ISSUE TITLE
Ticket Settings - Promo Codes - Ticket limit vs code use limit producing inconsistent results

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#84] opened 2019-04-08 17:01 UTC
relates to big-neon/bigneon#45
Steps to reproduce
- Set ticket limit for a ticket type to 1
- Create promo code with a max per customer use limit of 3
- Apply the code during the checkout flow
- Attempt to buy 3 tickets
- Attempt to buy 2 tickets

Expected behavior: 
- I see "Max 1 ticket per customer" when I try and  increase the quantity beyond 1
- I receive an error "You have exceeded the max tickets per customer limit." when I attempt to continue in that state.
- If I ever exceed the max uses for the promo code, when I hit continue I should receive the message "Max of 3 uses for code [CODE] exceeded"

Actual behavior:
- When I increase quantity to 2 tickets no message is shown, it appears that it should work. I try and continue and it says "Exceeded limit per person per event"
- When I increase quantity to 3 tickets I see "there is a 3 ticket limit" (it still appears that it should work). I try and continue and receive the message "Exceeded limit per person per event"
- When I attempt to continue with just 1 ticket (the ticket type max uses, it allows me to goto cart)

<img width="1440" alt="Buy_tickets_-_This_is_the_event_name" src="https://user-images.githubusercontent.com/456953/55742533-c5f39000-59e4-11e9-9944-7c9353d7939f.png">
<img width="1440" alt="Buy_tickets_-_This_is_the_event_name" src="https://user-images.githubusercontent.com/456953/55742626-f4716b00-59e4-11e9-84a4-8211b47bd349.png">

**Comment by Timo614** [comment] 2019-04-09 15:52
Sorry @zmelamed one more clarification just want to make sure I'm not misunderstanding something.

So looking over our current ticket limit logic:
https://github.com/big-neon/bn-api/blob/master/db/src/models/orders.rs#L761
https://github.com/big-neon/bn-api/blob/master/db/src/models/orders.rs#L915

I've confirmed:
- We don't currently do any bn-api based validations on the code use limit
- Currently the logic is setup to ignore the ticket limit when a hold is in use

So right now if a hold has a `max_per_user` value of 3 and a ticket type has a `limit_per_person` of 1 then they can buy up to 3 as it's ignoring the ticket type in that case. 

Since the code isn't supported right now it's falling into the logic for the ticket type and only validating against that which explains what you were seeing. 

It seems like the frontend is currently setup with the assumption that if the code has a `max_tickets_per_user` set then it overrides any value with the ticket type.

So I guess the fixes here are:
- Add support for code `max_tickets_per_user` in the check limit logic
- Either add support for the code `max_tickets_per_user` always overriding ticket type or adjust the check limits logic to no longer treat holds/codes as overriding the limit but just appending an additional limitation onto the validations
- Depending upon the second item either leave the frontend alone (assuming it still shows the limit of 1 when outside of a code context) or adjust the frontend to properly show the ticket type warning even if in the context of a hold or code order

I'm guessing given the issue description the latter is ideal so working in that direction for this.

**Comment by Timo614** [comment] 2019-04-09 17:24
Just leaving a note here: I did end up finding a validation on the code max per user it just was in the form of a db validation versus the update_quantities limit_check validation we use normally. Going to retire that approach in favor of the existing as it's clearer to follow the logic and the existing validation is something I added 5 months ago (https://github.com/big-neon/bn-api/blame/master/db/src/models/order_items.rs#L294) as we were in the process of getting the cart API set, etc. so was still a bit fluid.

**Comment by Timo614** [comment] 2019-04-09 19:42
Took me a little bit to sort out the bn-web side but after investigating a bit it looks like this is entirely a bn-api issue. We provide ticket types back with the redemption code show action which then are used in place of the ones provided during the normal API lookup. That call is currently passing the hold and code max uses values back without first checking if the ticket type limit is smaller than that value. Should be a straightforward fix on that side. 
https://github.com/big-neon/bn-api/blob/master/api/src/controllers/redemption_codes.rs#L80 
https://github.com/big-neon/bn-api/blob/master/api/src/models/user_display_ticket_type.rs#L88

In the process of testing I did run into some bn-web issues. Will follow up but marking them here so I don't lose track.

- Adding and removing a discount doesn't reset the state correctly (new limit is still active ie: hold's limit of 2 still applies even if ticket type has a limit of 4, the limit text for the hold doesn't disappear, if a hold was sold out and you remove the redemption code the quantity selectors do not reappear)
- Switching from a higher limit to a lower limit via redemption codes (ticket type limit of 4, hold limit of 3) with a quantity set above the lower limit (in this case set to 4) does not show limit text and allows invalid selection (after applying the redemption code the quantity is still set to 4 above the hold's limit). It should notice the set quantity is above the new limit and trigger the limit text and set the quantity down to the new limit.
- If I add discount code applied tickets to the cart, refresh my browser window, and then attempt to change the quantity of tickets in the cart the discount code is lost

I'll follow up with a bn-api pull request shortly.

**Comment by nine-tari** [comment] 2019-05-23 18:59
Moved to QA as this was merged awhile back before we moved over to the new system.

**Comment by mikethetike** [comment] 2019-05-28 08:14
@zmelamed If the ticket type has a limit of 1 and the promo code has a limit of 3, can a single user buy 3 via the promocode and 1 without the code (total 4)?

**Comment by Anziskavds** [comment] 2019-05-28 11:52
Steps to reproduce:

- I have set a ticket limit to 1 ticket per customer
- I have created a promo code with a max per customer use limit of 3
- I tried to buy more than 1 ticket at a time using the promo code created, which it didn't allow me to and gave me "You have exceeded the max tickets per customer limit" message.
- Can't purchase more than one ticket at a time even when the promo code is used.

**Comment by Timo614** [comment] 2019-05-28 12:51
>> If I ever exceed the max uses for the promo code, when I hit continue I should receive the message "Max of 3 uses for code [CODE] exceeded"

> If the ticket type has a limit of 1 shouldn't that prevent the user from ever reaching the max uses? Or is this message more for situations where the ticket type limit is larger than the promo codes max uses and that scenario when you reach it prior?

> Correct this is just to explain how to handle that situation when it does occcur

https://github.com/big-neon/bigneon/issues/84#issuecomment-481256627
https://github.com/big-neon/bigneon/issues/84#issuecomment-481262885

I asked Zach about the behavior earlier and he mentioned that the ticket type limit would prevent it so I think the test case 2 is invalid @Anziskavds.

**Comment by mikethetike** [comment] 2019-05-28 13:00
@zmelamed we need a ruling on the test cases. Are those correct?

**Comment by zmelamed** [comment] 2019-05-28 23:21
Ok, we just dug into this and the net out is that Ticket Type Limit should take precedence over promo code limits. Sorry for the confusion. So if the Ticket Type Limit is 2 and the max code limit is 3, the person should still only be able to purchase 2 tickets. 

Also uncovered in the conversation is that the only time a ticket type limit can be bypassed is through the box office by an org admin or higher, but that will be spec'd outside of this and require a few further clarifications, just wanted to add more context incase it's relevant.

**Comment by mikethetike** [comment] 2019-05-29 08:17
It's your call @zmelamed but I disagree. I think that it's much more flexible to have the promo code/hold limit override the ticket limit. This allows us to have:

* General public can buy max 1 ticket, but a promocode (e.g. media) can buy more. This also allows for comps, e.g. musician has 10 comps, but would have to have 10 accounts to buy them if the limit was 1 
* If the ticket type limit was higher, it allows us to have a one-use promo code (although I think that's what you are saying @zmelamed )

So I think that the promo-code/hold limit should always override the ticket limit, otherwise it doesn't make sense (as an org member) to populate them both.

**Comment by WolfManDan** [comment] 2019-05-29 20:46
interesting discussion. where did we net out on ticket limits and which one trumps?

**Comment by zmelamed** [comment] 2019-05-29 21:05
@Wolfmandan We're still having it. 

@mikethetike your cases are valid and touch on the reason I had originally suggested the promo to take precedence, but after talking it over with @harrisonlemon the required/expected behavior is to not allow a code to override the set limit for a given ticket type.

The default limit per customer ticket type is 10, it's very likely a client would want to set a lower limit for a discount/comp code use per customer which is why it's necessary.

There is a case to be made related to individuals hold being treated differently, but after discussing with @harrisonlemon it was decided that the expected behavior is that Ticket type limits take precedence. 

We also discussed the possibility of not allowing a code limit higher than the ticket type limit, displaying a message to inform the code creator, but we're not going down that road in the scope of this specific issue.

**Comment by mikethetike** [comment] 2019-05-30 07:51
I still disagree, but happy to go with the rules set out by @zmelamed and @harrisonlemon

**Comment by nine-tari** [comment] 2019-05-30 22:50
Sounds good, re: above. Moved this into the "Review/QA" pile since I think we're set here now.

We'll need to adjust test case 2 to have a higher ticket limit than the codes to see that logic in the test flow. It'll fail for the codes/holds if they reach their ticket limit prior to the ticket type limit so should show the proper error message we wanted here.

**Comment by Anziskavds** [comment] 2019-06-03 07:49
Reviewed:

-Set a ticket limit per customer to 4 and created a promo code with a ticket limit of 2 per customer.
-It allowed me to purchase 2 ticket with the promo code.
-Removed the promo code and added 4 tickets to my cart.
-Clicked on continue and received "You have exceeded the max tickets per customer limit".
-Added 2 tickets to my cart and it allowed me to purchase 2 tickets.
-Ticket limit of 4 tickets per customer reached and I wasn't allowed to purchase any more tickets. 
-Error messages received as it should be and seems like it's working.

**Comment by Anziskavds** [comment] 2019-06-05 11:48
Tested on Prod and works as expected.

**Closed by Anziskavds** 2019-06-05 11:48 UTC
Labels: bug
