### ISSUE TITLE
Reporting - Audit Reports - Ticket counts section showing multiple rows for the same ticket type

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bigneon#167] opened 2019-05-16 19:39 UTC
Context: The ticket counts section of the event/org level audit and summary audit reports should not be showing multiple line items for the same ticket type price point.

![screencapture-beta-bigneon-admin-events-9bdc1bba-7144-4b8b-9446-a095f14e9578-dashboard-reports-audit-2019-05-16-12_35_04.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/16288818-5380-482f-9f26-fb83a21ccfef)

**Comment by mikethetike** [comment] 2019-05-22 10:53
I'm really struggling to reproduce this locally. Is it possible that this is bad data?

**Comment by mikethetike** [comment] 2019-05-22 10:53
Adding @Anziskavds to see if she can reproduce it

**Comment by Timo614** [comment] 2019-05-22 16:08
I can see it via:
https://beta.bigneon.com/admin/events/9bdc1bba-7144-4b8b-9446-a095f14e9578/dashboard/reports/audit

I'll try to take a look.

One other oddity I noticed is the export CSV capability shows the ticket counts all rolled up (and correct) but the export PDF and the page itself show them broken down with this issue.

**Comment by Timo614** [comment] 2019-05-22 17:35
It looks like these are different price points but with the same prices:

```
online_sale_count: 2
...
ticket_name: "GA"
ticket_pricing_id: "066f8541-d048-472c-918d-92e641e27044"
```

```
online_sale_count: 20
...
ticket_name: "GA"
ticket_pricing_id: "193985b5-e1ce-4ab7-b899-834cbd45ba26"
```

![Screen Shot 2019-05-22 at 1 29 28 PM](https://user-images.githubusercontent.com/1319304/58195340-b464ff80-7c95-11e9-9106-8750ae19fee0.png)

This is done intentionally when a ticket type is edited to preserve the history:
https://github.com/big-neon/bn-api/blob/5c1dad6ba7570d0d62c257a3cbd6ff2889999103/db/src/models/ticket_types.rs#L147

I think the fix here is likely to just change the group by on the API side:
https://github.com/big-neon/bn-api/blob/5c1dad6ba7570d0d62c257a3cbd6ff2889999103/db/functions/ticket_sales_per_ticket_pricing.sql#L188

```
GROUP BY e.id, tt.id, tt.name, tt.status, tp.id, tp.name, tp.price_in_cents, gh.id, gh.name, gh.hold_type,
        gh.discount_in_cents, c.id, c.name, c.redemption_code, oi_promo_code_price.unit_price_in_cents;
```

to:

```
GROUP BY e.id, tt.id, tt.name, tt.status, tp.name, tp.price_in_cents, gh.id, gh.name, gh.hold_type,
        gh.discount_in_cents, c.id, c.name, c.redemption_code, oi_promo_code_price.unit_price_in_cents;
```

I'll take a look and file a new issue for that other thing I saw (the CSV output on the bn-web side not matching the page or PDF export for the event audit report).

**Comment by Timo614** [comment] 2019-05-22 18:08
I see why it was in the group by -- we're intentionally returning the ticket_pricing_id right now. This would bit us in other reports but we have put temp solutions in place previously:
https://github.com/big-neon/bn-web/blob/master/src/components/pages/admin/reports/eventSummaryAudit/SummaryAudit.js#L19

I'll make the changes here to remove the ticket_pricing_id, remove the temp solution above, etc. so we won't run into it again with this report and its consumers.

**Comment by Timo614** [comment] 2019-05-22 23:05
Also filed https://github.com/big-neon/bn-api/issues/1287 as well to make sure we're less aggressive about making new ticket pricing records here in the future as well. Right now any update call for a ticket type (even no changes) can trigger the old pricing record to be retired and a new added in its place with the same data.

We still need the associated changes from the PRs both for legacy ticket pricing records and for situations where a user sets a new price and then sets it back but with that other change we should have less clutter in the db as well. The changes here address the higher priority aspect of things though; the other issue isn't too pressing with these PRs in place.

**Comment by Anziskavds** [comment] 2019-05-23 07:28
Steps to reproduce:
- Created a new event with two ticket types
- First I bought golden circle tickets then I created the second ticket type (General Admission)
- I bought some golden circle tickets again along with General Admission tickets
- After the second time I bought tickets multiple lines for the same ticket type (Golden Circle) appeared on the "Event Audit Report" 

https://cl.ly/cc67a34252eb

**Comment by Anziskavds** [comment] 2019-05-23 08:45
Still happening on bn-api v1.0.124
https://cl.ly/fa4c7be173ae

**Comment by Timo614** [comment] 2019-05-23 12:13
What environment are you testing with? The beta server hasn't been updated it looks like as it's still returning the `ticket_pricing_id` with the response (it was removed as part of the bn-api changes).

**Comment by Timo614** [comment] 2019-05-23 12:28
I attempted the steps and not seeing it after the changes in the associated PR:

Only one ticket type available, purchasing 4:
![Screen Shot 2019-05-23 at 8 20 15 AM](https://user-images.githubusercontent.com/1319304/58252482-39065b00-7d34-11e9-8a40-3fb4604dcccd.png)

Second ticket type is now available after adding, purchasing 4 of each:
![Screen Shot 2019-05-23 at 8 22 17 AM](https://user-images.githubusercontent.com/1319304/58252483-39065b00-7d34-11e9-86d3-708d0267e3cf.png)

Result from the audit report:
![Screen Shot 2019-05-23 at 8 23 21 AM](https://user-images.githubusercontent.com/1319304/58252484-39065b00-7d34-11e9-9bd8-0f6e955f4feb.png)

Maybe it's an issue with whatever environment it was tried on? If it was local did you update the functions?

**Comment by Timo614** [comment] 2019-05-23 20:38
I confirmed this is happening on devops https://develop.bigneon.com/admin/events/ee7b8e4a-a123-42bf-b514-3ffdf29e6e66/dashboard/reports/audit when I follow the same steps.

Going to quickly confirm my suspicion that locally this would occur if the functions were not updated and if so will reach to confirm if perhaps that step in the process doesn't happen automatically there.

**Comment by Timo614** [comment] 2019-05-23 20:44
Yeah confirmed if the function isn't run then I see the same issue still:

![Screen Shot 2019-05-23 at 4 43 12 PM](https://user-images.githubusercontent.com/1319304/58285039-fbc4bc00-7d79-11e9-974e-1dbf5699c4b1.png)
![Screen Shot 2019-05-23 at 4 43 36 PM](https://user-images.githubusercontent.com/1319304/58285040-fbc4bc00-7d79-11e9-9ce4-ab3879b4f73f.png)

I'll reach out in chat to see if someone can update devops.

**Comment by Timo614** [comment] 2019-05-28 08:50
It does look like it was a devops deployment issue as the it is now resolved without anything else changing: https://develop.bigneon.com/admin/events/ee7b8e4a-a123-42bf-b514-3ffdf29e6e66/dashboard/reports/audit

**Comment by Anziskavds** [comment] 2019-05-28 12:46
Reviewed and it is working as expected(No multiple lines appeared on the same ticket type).
V 1.0.128

https://cl.ly/7a95bec8837f

**Closed** 2019-05-30 12:41 UTC
Labels: bug
